export type Article = { datePublished?: string; dateModified?: string; slug: string; category: string; title: string; description: string; readTime: string; sections: { title: string; text: string }[]; sources: { title: string; url: string }[] };
export const articles: Article[] = [
  { slug: 'antes-de-registrar-sua-marca', category: 'MARCAS', title: 'Antes de registrar sua marca, entenda o que está em jogo.', description: 'Nome, domínio e registro: entender as diferenças ajuda a tomar uma decisão mais consciente.', readTime: '2 min', sections: [
    { title: 'O nome é apenas o começo', text: 'Escolher um nome envolve muito mais do que sonoridade. A marca identifica produtos ou serviços e concentra parte da reputação do negócio. O registro no INPI é o caminho para buscar sua proteção, conforme os limites e requisitos aplicáveis.' },
    { title: 'CNPJ, domínio e marca são coisas diferentes', text: 'Formalizar a empresa e reservar um endereço na internet não substituem o registro de marca. Cada instrumento tem uma finalidade. Por isso, vale analisar esses elementos em conjunto, sem presumir que um protege automaticamente o outro.' },
    { title: 'Pesquisar antes de investir', text: 'O INPI recomenda a busca por marcas semelhantes. A análise precisa considerar também os produtos e serviços envolvidos. Ela ajuda a reconhecer possíveis conflitos antes de investir em identidade, comunicação ou expansão.' },
    { title: 'Uma decisão com contexto', text: 'Leve para a primeira conversa o nome que usa ou pretende usar, uma descrição da atividade e seus planos de crescimento. A orientação da Velmont parte desse contexto para discutir riscos e caminhos. A apresentação de um pedido não representa aprovação garantida.' },
  ], sources: [{title:'INPI — Guia básico de marcas',url:'https://www.gov.br/inpi/pt-br/servicos/marcas/guia-basico'},{title:'INPI — Marca, nome empresarial e domínio',url:'https://www.gov.br/inpi/pt-br/plataforma-integrada-de-atendimento/marca-x-nome-empresarial-x-dominio'}] },
  { slug: 'software-tambem-e-patrimonio', category: 'SOFTWARE', title: 'Seu software também é patrimônio. Você está cuidando dele?', description: 'Autoria, código e titularidade precisam fazer parte da estratégia de um negócio digital.', readTime:'2 min', sections:[
    { title:'Além do produto que aparece na tela',text:'Um software reúne decisões, conhecimento e investimento. A proteção jurídica do programa de computador se relaciona à expressão do código. Ela não significa, por si só, exclusividade sobre toda ideia ou funcionalidade de um produto.' },
    { title:'O papel do registro',text:'Segundo o INPI, o registro de programa de computador contribui para a segurança jurídica em disputas sobre autoria ou titularidade. Entender qual versão será registrada e organizar a documentação faz parte desse cuidado.' },
    { title:'Quem criou? Quem é titular?',text:'Quando sócios, empregados, parceiros ou fornecedores participam do desenvolvimento, as relações precisam estar claras. Contratos, cessão e licenciamento merecem análise no contexto de cada projeto. A Velmont trabalha essas frentes de forma integrada à estratégia do negócio.' },
    { title:'Um bom ponto de partida',text:'Organize o histórico do projeto, identifique os participantes e reúna os contratos existentes. Essas informações ajudam a primeira conversa. A análise individual define os documentos e os próximos passos adequados.' },
  ],sources:[{title:'INPI — Guia básico de programa de computador',url:'https://www.gov.br/inpi/pt-br/servicos/programas-de-computador/guia-basico'},{title:'INPI — Perguntas frequentes sobre programas de computador',url:'https://www.gov.br/inpi/pt-br/acesso-a-informacao/perguntas-frequentes/programas-de-computador'}] },
  {slug:'inovacao-e-patente',category:'PATENTES',title:'Da inovação à proteção: o que analisar antes de uma patente.',description:'Uma criação promissora precisa ser avaliada com critérios técnicos e visão estratégica.',readTime:'2 min',sections:[
    {title:'Qual problema sua criação resolve?',text:'A primeira conversa começa pela solução técnica e pelo contexto do negócio. Descrever o problema, o funcionamento e o que sua criação traz de diferente ajuda a organizar a análise. Não é necessário começar com uma promessa de patente.'},
    {title:'O que já existe importa',text:'A busca de anterioridade reúne informações sobre tecnologias existentes. Para uma patente de invenção, os requisitos incluem novidade, atividade inventiva e aplicação industrial. A pesquisa e a avaliação técnica ajudam a compreender o cenário, sem antecipar a decisão do INPI.'},
    {title:'Nem todo ativo segue o mesmo caminho',text:'Patente de invenção, modelo de utilidade e desenho industrial têm objetos e requisitos distintos. Identificar o que se pretende proteger é essencial para discutir a alternativa adequada. A aparência de um produto e sua solução técnica podem exigir análises diferentes.'},
    {title:'Converse antes de definir a estratégia',text:'Reúna descrições, desenhos e o histórico de desenvolvimento. Na conversa inicial, evite enviar informações técnicas confidenciais até alinhar com a equipe a forma adequada de compartilhamento. O objetivo é entender o projeto e organizar uma análise responsável.'},
  ],sources:[{title:'INPI — Guia básico de patentes',url:'https://www.gov.br/inpi/pt-br/servicos/patentes/guia-basico/guia-basico/'},{title:'INPI — Serviços de propriedade industrial',url:'https://www.gov.br/inpi/pt-br/servicos'}]},
];

export const articleVisuals: Record<string, { image: string; width?: number; height?: number; alt: string; service: string; serviceLabel: string }> = {
 MARCAS: { image: 'velmont-trademark-bottle', width: 1192, height: 1320, alt: 'Frasco com o nome Velmont delimitado por uma moldura dourada, ilustração de proteção de marca', service: 'marcas', serviceLabel: 'Registro e proteção de marcas' },
 SOFTWARE: { image: 'velmont-software-authorship', alt: 'Camadas de uma aplicação digital, ilustração de autoria de software', service: 'software', serviceLabel: 'Registro e proteção de software' },
 PATENTES: { image: 'velmont-patent-engineering', alt: 'Componentes mecânicos em vista explodida, ilustração de uma invenção', service: 'patentes', serviceLabel: 'Patentes e desenho industrial' },
};
