import { whatsappUrl } from '@/lib/site';
import { Header, Footer } from './home';
import { Arrow } from './icons';
import { Breadcrumbs } from './breadcrumbs';
import { articles, articleVisuals, type Article } from '@/content/insights';
const dateLabel = (date: string) => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(date));
export function ArticleView({ article: a }: { article: Article }) {
  const visual = articleVisuals[a.category];
  return <><Header inner /><main className="editorial wrap" id="inicio"><Breadcrumbs current={a.title} article /><h1>{a.title}</h1><p className="editorial-intro">{a.description}</p><div className="article-byline"><span>Por <a href="/#essencia" rel="author">Velmont</a></span><span>{a.category} · {a.readTime} de leitura</span>{a.datePublished && <span>Publicado em <time dateTime={a.datePublished}>{dateLabel(a.datePublished)}</time></span>}{a.dateModified && <span>Atualizado em <time dateTime={a.dateModified}>{dateLabel(a.dateModified)}</time></span>}</div><img className="article-cover" src={`/generated/${visual.image}-1000.webp`} srcSet={`/generated/${visual.image}-640.webp 640w, /generated/${visual.image}-1000.webp 1000w`} sizes="(max-width: 767px) 100vw, 1000px" width="1000" height="1000" alt={visual.alt} decoding="async" /><article className="article-body">{a.sections.map(s => <section key={s.title}><h2>{s.title}</h2><p>{s.text}</p></section>)}<aside className="article-sources"><p>Referências para aprofundar</p>{a.sources.map(s => <a className="article-source-link" href={s.url} target="_blank" rel="noopener noreferrer" key={s.url}>{s.title}<Arrow /></a>)}<p className="article-note">Conteúdo informativo. As possibilidades de proteção dependem da análise do caso.</p></aside><div className="article-cta"><h2>Como isso se aplica<br /><em>ao seu negócio?</em></h2><a className="text-link" href={`/#${visual.service}`}>Conheça nossa atuação em {a.category.toLowerCase()} <Arrow /></a><br /><a className="text-link" href={whatsappUrl()} target="_blank" rel="noopener noreferrer">Solicitar uma análise estratégica <Arrow /></a></div><aside className="article-related"><h2>Continue a leitura</h2>{articles.filter(item => item.slug !== a.slug).map(item => <a href={`/insights/${item.slug}`} key={item.slug}>{item.title} <Arrow /></a>)}</aside></article></main><Footer /></>;
}
