// One-off: writes the SQL that imports the launch articles into the CMS.
// Run with: node --import tsx scripts/generate-legacy-import.ts > supabase/migrations/<ts>_import_launch_articles.sql
import { legacyPosts } from '../lib/blog/legacy';

const lit = (value: string) => `'${value.replace(/'/g, "''")}'`;
const json = (value: unknown) => `${lit(JSON.stringify(value))}::jsonb`;
const lines = [
  '-- Imports the three launch articles (previously in content/insights.ts).',
  '-- Dates stay empty: no publication date was ever confirmed for them.',
  '-- Generated by scripts/generate-legacy-import.ts. Idempotent.',
  '',
];
legacyPosts.forEach((p, i) => {
  const createdAt = lit(`2026-09-06T12:00:0${legacyPosts.length - i}Z`);
  lines.push(
    `insert into public.articles (title, slug, excerpt, content, author_key, category, sources, reading_minutes, status, legacy_import, created_at, updated_at)`,
    `values (${lit(p.title)}, ${lit(p.slug)}, ${lit(p.excerpt)}, ${json(p.content)}, ${lit(p.author)}, ${lit(p.category)}, ${json(p.sources)}, ${p.readingMinutes}, 'published', true, ${createdAt}, ${createdAt})`,
    `on conflict (slug) do nothing;`,
    '',
  );
});
lines.push(
  `insert into public.published_articles (article_id, slug, title, excerpt, content, category, tags, author_key, sources, robots_index, reading_minutes, created_at, source_version)`,
  `select a.id, a.slug, a.title, a.excerpt, a.content, a.category, a.tags, a.author_key, a.sources, a.robots_index, a.reading_minutes, a.created_at, a.version`,
  `from public.articles a`,
  `where a.legacy_import and a.status = 'published'`,
  `on conflict (article_id) do nothing;`,
  '',
);
process.stdout.write(lines.join('\n'));
